entry_list = [address,annote,author,booktitle,chapter,crossref,doi,edition,editor,email,howpublished,institution,journal,month,note,number,organisation,pages,publisher,school,series,title,Type,volume,year]
CREATE TABLE IF NOT EXISTS entries (
    id INTEGER PRIMARY KEY,
    ref_type TEXT,
    address TEXT,
    annote TEXT,
    author TEXT,
    booktitle TEXT,
    chapter TEXT,
    crossref TEXT,
    doi TEXT,
    edition TEXT,
    editor TEXT,
    email TEXT,
    howpublished TEXT,
    institution TEXT,
    journal TEXT,
    month TEXT,
    note TEXT,
    number TEXT,
    organisation TEXT,
    pages TEXT,
    publisher TEXT,
    school TEXT,
    series TEXT,
    title TEXT,
    Type TEXT,
    volume TEXT,
    year TEXT,
);